name: Release

on:
  release:
    types: [ released ]

jobs:
  test:
    name: Run Tests
    uses: ./.github/workflows/PackageTest.yml
    secrets: inherit

  build:
    name: Build Source Distribution
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Poetry
        run: pip install poetry

      # Get the new package version from the release tag
      # Git release tags are expected to start with "refs/tags/v"
      - name: Set package version
        run: |
          tag=${{github.ref}}
          poetry version "${tag#refs/tags/v}"

      - name: Build package
        run: poetry build -v

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          user: ${{ secrets.PYPI_USER }}
          password: ${{ secrets.PYPI_PASSWORD }}
